Personal details css
front-end-by-rimantas/27-grupe-portfolio-personal pull request #63
Opened 2021-05-28 11:34 UTC by mantodinas

Personal details ccs styling and html small fix

2021-05-28 12:43 UTC, Justas26 approved these changes

2021-05-28 15:36 UTC, gretane approved these changes
Cool
 - Siūlau tik 28 eilutėj vietoj border-radius daryti šešėlį (box-shadow)
 - Ir kai sumažėja iki mobilios versijos, kad tekstas nebūtų "prilipęs" prie nuotraukos, o būtų po ja bent šioks toks tarpas

2021-05-29 06:58 UTC, Mantachkis requested changes
Per anksti nukrenta tekstas po nuotrauka.
Nuo 650 px mažinant plotį tekstas nebetelpa į langą.

2021-05-29 11:30 UTC, Justas26 approved these changes

2021-05-30 12:19 UTC, Mantachkis approved these changes

2021-05-30 12:19 UTC, merged